const colors = {
  light: {
    text: "#0A0A14",
    tint: "#7C6FF7",
    background: "#F8F8FF",
    foreground: "#0A0A14",
    card: "#FFFFFF",
    cardForeground: "#0A0A14",
    primary: "#7C6FF7",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0FB",
    secondaryForeground: "#1A1A2A",
    muted: "#F0F0FB",
    mutedForeground: "#7575A0",
    accent: "#FF6B6B",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0F0",
    input: "#F0F0FB",
    success: "#4ECDC4",
    warning: "#FFB347",
    coral: "#FF6B6B",
    teal: "#4ECDC4",
    amber: "#FFB347",
    purple: "#7C6FF7",
  },
  dark: {
    text: "#F2F2FF",
    tint: "#7C6FF7",
    background: "#0A0A14",
    foreground: "#F2F2FF",
    card: "#13131F",
    cardForeground: "#F2F2FF",
    primary: "#7C6FF7",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A28",
    secondaryForeground: "#F2F2FF",
    muted: "#1A1A28",
    mutedForeground: "#7575A0",
    accent: "#FF6B6B",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#252538",
    input: "#1A1A28",
    success: "#4ECDC4",
    warning: "#FFB347",
    coral: "#FF6B6B",
    teal: "#4ECDC4",
    amber: "#FFB347",
    purple: "#7C6FF7",
  },
  radius: 16,
};

export default colors;
